const arr = [
  {
      id: 1,
      datetime: '2022-01-20 10:16:55',
      title: 'First certificate',
      tags: 'tag1 tag2 tag3',
      description: 'long long long description',
      duration: '20',
      price: 15,
      view: false,
      edit: false,
      delete: false
  },
  {
      id: 2,
      datetime: '2022-01-20 10:16:50',
      title: 'Second certificate',
      tags: 'tag1 tag2 tag3',
      description: 'long long long description',
      duration: '20',
      price: 15,
      view: false,
      edit: false,
      delete: false
  },
  {
      id: 3,
      datetime: '2022-01-20 10:16:49',
      title: 'Third certificate',
      tags: 'tag1 tag2 tag3',
      description: 'long long long description',
      duration: '20',
      price: 15,
      view: false,
      edit: false,
      delete: false
  },
  {
      id: 4,
      datetime: '2022-01-20 10:17:00',
      title: 'Fourth certificate',
      tags: 'tag1 tag2 tag3',
      description: 'long long long description',
      duration: '20',
      price: 15,
      view: false,
      edit: false,
      delete: false
  },
  {
      id: 5,
      datetime: '2022-01-20 10:16:55',
      title: 'Fifth certificate',
      tags: 'tag1 tag2 tag3',
      description: 'long long long description',
      duration: '20',
      price: 15,
      view: false,
      edit: false,
      delete: false
  },
  {
      id: 6,
      datetime: '2022-01-20 10:16:50',
      title: 'Sixth certificate',
      tags: 'tag1 tag2 tag3',
      description: 'long long long description',
      duration: '20',
      price: 15,
      view: false,
      edit: false,
      delete: false
  },
  {
      id: 7,
      datetime: '2022-01-20 10:16:49',
      title: 'Seventh certificate',
      tags: 'tag1 tag2 tag3',
      description: 'long long long description',
      duration: '20',
      price: 15,
      view: false,
      edit: false,
      delete: false
  },
  {
      id: 8,
      datetime: '2022-01-20 10:17:00',
      title: 'Eighth certificate',
      tags: 'tag1 tag2 tag3',
      description: 'long long long description',
      duration: '20',
      price: 15,
      view: false,
      edit: false,
      delete: false
  },
  {
      id: 9,
      datetime: '2022-01-20 10:16:55',
      title: 'Nineth certificate',
      tags: 'tag1 tag2 tag3',
      description: 'long long long description',
      duration: '20',
      price: 15,
      view: false,
      edit: false,
      delete: false
  },
  {
      id: 10,
      datetime: '2022-01-20 10:16:50',
      title: 'Tenth certificate',
      tags: 'tag1 tag2 tag3',
      description: 'long long long description',
      duration: '20',
      price: 15,
      view: false,
      edit: false,
      delete: false
  },
  {
      id: 11,
      datetime: '2022-01-20 10:16:49',
      title: 'Eleventh certificate',
      tags: 'tag1 tag2 tag3',
      description: 'long long long description',
      duration: '20',
      price: 15,
      view: false,
      edit: false,
      delete: false
  },
  {
      id: 12,
      datetime: '2022-01-20 10:17:00',
      title: 'Twelve certificate',
      tags: 'tag1 tag2 tag3',
      description: 'long long long description',
      duration: '20',
      price: 15,
      view: false,
      edit: false,
      delete: false
  },
  {
    id: 13,
    datetime: '2022-01-20 10:17:00',
    title: 'Thirtetefasd certificate',
    tags: 'saffa tag2 tag3',
    description: 'long long long description',
    duration: '20',
    price: 15,
    view: false,
    edit: false,
    delete: false
}
]

export default arr;
